spring.application.name=the-greatest-adventure-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/wedding_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

jwt.secret=bG9uZy1zZWNyZXQta2V5LWZvci10aGUtZ3JlYXRlc3QtYWR2ZW50dXJlLTIwMjY=
jwt.expiration=86400000