spring.application.name=the-greatest-adventure-backend

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/wedding_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

#SECURITY
jwt.secret=bG9uZy1zZWNyZXQta2V5LWZvci10aGUtZ3JlYXRlc3QtYWR2ZW50dXJlLTIwMjY=
jwt.expiration=86400000

#EMAIL
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

wedding.invite.base-url=http://localhost:3000/invito